export const main = [
  {
    EN : "In 2008, Iceland suffered its worst financial crisis in modern history. Its people were angry. They believed the crisis was enabled by a government that was not responsive to them. ",
    IS : "Árið 2008 varð Ísland fyrir mesta fjármálahruni samtímasögunnar. Mikil reiði ríkti meðal almennings. Margir töldu að stjórnvöld bæru ábyrgð þar sem þau hefðu hvorki hlustað á varnaðarorð  né brugðist við aðstæðum."
  }, {
    EN : "So they launched the most ambitious project to crowdsource a new constitution by any people anywhere. First, a random sample of 1,000 gathered to identify the values the new constitution should embody. Then, more than 500 people ran to serve on a constitutional council to draft the constitution. Twenty-five were elected. And then for four months, they drafted a constitution, posting drafts to Facebook and taking comments from people around the world.",
    IS : "Hafist var handa við það metnaðarfulla verkefni að skrifa nýja stjórnarskrá með lýðræðislegasta hætti sem um getur á heimsvísu. Fyrst var haldinn þjóðfundur þar sem 1.000 borgarar valdir af handahófi lögðu fram þau gildi sem nýja stjórnarskráin skyldi byggja á. Síðan buðu yfir 500 manns sig fram til setu í stjórnlagaráði til að skrifa nýja stjórnarskrá. Tuttuguogfimm voru kjörnir. Á fjórum mánuðum skrifaði stjórnlagaráð nýja stjórnarskrá sem sett var á netið jafnóðum og hún varð til þar sem almeningur fékk tækifæri til að bera upp tillögur og gera athugasemdir."
  }, {
    EN : "In 2012, in a national referendum, 2/3ds voted to tell their parliament to ratify a constitution based on the constitution the people had drafted. So far, Parliament has ignored that referendum. Instead, it has failed to take up even the most unconstroversial changes proposed in the new constitution. And as the recent Panama Papers Crisis reveals, the consequence is a government the people still don't trust.",
    IS : "Árið 2012 var svo haldin þjóðaratkvæðagreiðsla þar sem yfir 2/3 hlutar kjósenda sögðu að Alþingi skyldi gera drög stjórnlagaráðs að grundvelli nýrrar stjórnarskrár fyrir Ísland. Enn sem komið er hefur Alþingi hunsað niðurstöður þjóðaratkvæðagreiðslunnar. Þinginu hefur ekki einu sinni tekist að gera smávægilegar og óumdeildar breytingar á stjórnarskránni á þessum tíma. Viðbrögð við uppljóstrunum í Panama-skjölunum sýna ljóslega afleiðingar þessa, að almenningur treystir ekki stjórnvöldum."
  }, {
    EN : "We are citizens, based in Iceland, but supported by believers in democracy from around the world. We are not politicians. None of us is running for any office, anywhere. Instead, we are citizens rallying Iceland to send one clear message to its Parliament: You work for us. And we are asking voters in Iceland — whether on the right or left — to commit to vote only for parties that have promised to \"make ratifying a constitution based on the 2012 draft a top priority in the new government.\"",
    IS : "Við erum borgarar búsettir á Íslandi en njótum stuðning frá lýðræðissinnum um allan heim. Við erum ekki stjórnmálamenn. Ekkert okkar sækist eftir opinberu embætti. Við erum borgarar sem höfum það markmið að sameina Íslendinga um einföld og skýr skilaboð til Alþingis: Þið vinnið fyrir okkur. Því biðjum við íslenska kjósendur - hvort sem þeir hallast til hægri eða vinstri - að kjósa einungis þá stjórnmálaflokka sem hafa lofað að gera að forgangsmáli á nýju þingi, að setja Íslandi nýja stjórnarskrá sem grundvallast á drögum stjórnlagaráðs."
  }, {
    EN : "All the money we raise will be devoted to spreading this message. All of the organizers of this campaign are volunteers. All of us need you to help as well.",
    IS : "Öllum fjármunum sem safnast með þessari herferð verður varið í að koma þessum skilaboðum á framfæri. Skipuleggjendur þessarar herferðar vinna alfarið að máli þessu í sjálfboðavinnu. Við þurfum þína aðstoð."
  }, {
    EN : "Join us — for democracy in Iceland, for democracy everywhere.",
    IS : "Gangið í lið með okkur - fyrir lýðræði á Íslandi og um allan heim."
  }
];

export const us = {
  EN: "This campaign is sponsored by the Icelandic Constitution Society (Stjórnarskrárfélagið), a registered non-profit organisation in Iceland. All funds raised in the campaign will be used to rally voters in Iceland to demand a Parliament that listens and to provide constant pressure to the new Parliament so that elected members deliver their promises on this important matter. All expenses will be fully and publicly disclosed. Any remaining funds will be used to support democracy movements internationally.",
  IS: "Herferð þessi er unnin af Stjórnarskrárfélaginu, kt. 590810-2230, sem er almennt félag sem hefur ekki atvinnustarfsemi. Allir fjármunir sem safnast með þessari herferð verða notaðir til þess að hvetja kjósendur til þess að fá Alþingi til að sinna kröfu um nýja stjórnarskrá og veita þinginu aðhald eftir að það hefur komið saman til þess að loforðum um stjórnarskrárumbætur verði fylgt eftir. Verður gerð grein fyrir því með gegnsæum og opinberum hætti hvernig fjármunum sem safnast er varið. Verði einhver afgangur af þeirri fjárhæð sem safnast mun honum varið í að styðja lýðræðisumbætur á alþjóðlegum vettvangi."
};
