export
default {
  videoPoints: [{
    text: {
      "EN": [
        "The new constitution ensures national ownership and sustainable development of Iceland's national resources.",
        "English subtitles available."
      ],
      "IS": [
        "Í nýju stjórnarskránni er almenningi tryggð eign á náttúruauðlindum og gerð krafa um að þeim sé ráðstafað með sjálfstæðum hætti og þannig að fullt verð komi fyrir. "
      ],
    },
    video: "https://www.youtube.com/embed/eDlIMHfROX4",
  }, {
    text: {
      "EN": ["The new constitution tackles corruption.",
        "For example, members of Parliament will be prohibited from participating in any matters which concerns their special and significant interest, or the interests of persons with whom they have close ties.",
        "They must also disclose information on their financial interests. This is very important in the light of the Panama Papers scandal, which forced Iceland's (now former) Prime Minister to resign this past April, after it was revealed that he and his wife had set up a company through Mossack Fonseca.",
        "English subtitles available"
      ],
      "IS": [
        "Nýja stjórnarskráin kveður á um að Alþingismönnum sé óheimilt að taka þátt í meðferð þingmála ef þeir hafa sérstakra og verulegra hagsmuna að gæta eða aðrir sem eru þeim nákomnir. Einnig er tekið fram að alþingismenn beri skyldu til að veita upplýsingar um fjárhagslega hagsmuni sína. Í ljósi uppljóstrana úr Panama-skjölum liggur fyrir að slík ákvæði þurfa að vera í stjónarskrá."
      ],
    },
    video: "https://www.youtube.com/embed/xUBmMbwjvR8",
  }, {
    text: {
      EN: [
        "The natural beauty of Iceland is considered one of the great wonders of the world.",
        "Entertainer and journalist Omar Ragnarsson talks about the strong provisions on the protection of nature and sustainable use of natural resources in the new constitution in this video.",
        "English subtitles available"
      ],
      IS: [
        "Íslensk náttúra er talin ein af undrum veraldar eins og Ómar Ragnarsson bendir hér á. Í drögum Stjórnalagaráðs að nýrri stjórnarskrá er að finna mjög sterk ákvæði um náttúruvernd auk kröfu um sjálfbærrar nýtingar náttúruauðlinda."
      ],
    },
    video: "https://www.youtube.com/embed/RxguS56TnxQ",
  }, ],
  articles: [{
    title: {
      EN: "Does the Parliament ignore the Sovereignty of the Icelandic Nation?",
      IS: "Hunsar Alþingi fullveldi íslensku þjóðarinnar?",
    },
    languages: ["EN", "IS"],
    author: "Lawrence Lessig",
    translator: "Ólöf Pétursdóttir",
    authorPics: ["/img/authors/lessig.jpg"],
    authorBios: {
      EN: [
        "Lester Lawrence \"Larry\" Lessig III is an American academic, attorney, and political activist. He is the Roy L. Furman Professor of Law at Harvard Law School and the former director of the Edmond J. Safra Center for Ethics at Harvard University"
      ],
      IS: [
        "Lawrence Lessig, prófessor við lagadeild Harvard-­háskóla í Bandaríkjunum.",
      ],
    },
    text: {
      EN: [
        "In the history of constitutions across the world, America has had a unique place: Ours was the first constitution ratified by the people in convention. But Iceland has now done something much more significant: For the first time in the history of the world, and using a technology only possible in the 21st century, the people of a nation have crafted their own constitution through an open and inclusive crowd-sourcing process. Yet astonishingly, that constitution remains unenforced.",
        "As everyone in this nation knows, after the financial disasters of 2008, the citizens of Iceland began a process to claim back their own sovereignty. Building on the values identified by 1,000 randomly selected citizens, Icelanders launched a process to crowdsource a new constitution. That initiative was then ratified when the Parliament established a procedure for selecting delegates to a drafting commission. More than 500 citizens ran to serve on that 25 person commission. Over four months, the commissioners met to draft a constitution, with their work made available for public comment throughout the process. More than 3600 comments were offered by the public, leading to scores of modifications. The final draft was then sent to the parliament and to the people. More than 2/3ds of voters endorsed the document as the basis of a new constitution.",
        "Never in the history of constitutionalism has anything like this ever been done. If democracy is rule by the people - if the sovereignty of a democratic nation is ultimately the people - then this process and the constitution it produced is as authentic and binding as any in the world. Yet the parliament of Iceland has refused to allow this constitution to go into effect. And the question that anyone in the movements for democracy across the world must ask is just this: By what right?",
        "No doubt, the procedure for crafting and ultimately ratifying the constitution included as the final step Parliament’s sanction-just as the procedure for selecting a government in Britain is subject ultimately to the Queen’s sanction. But the Queen understands the limited power that right conveys-if Britain is to call itself a democracy. And the same is true of Iceland. When the people have acted as they have here-by crafting a constitution in the most inclusive and reflective way that has ever, in the history of constitutionalism, happened, and then endorsed that work by a popular vote, by what moral authority does the Parliament now say no? No doubt, there are parts of the constitution that some don’t like. But democracy is not a promise of perfection. And no constitution in the history of the world has ever been loved by everyone it affected - just ask the million African slaves whose freedom was made unconstitutional through 1808 by America’s popularly ratified constitution. The question for Iceland is who is sovereign? Is it the people or is it not? And if it is the people, will the people demand that their will be respected?",
        "This is a question, of course, for Iceland. But it is also a question for the world. As notions of sovereignty have evolved across time - from god, to a king, to an elite, and finally, to the people - the people of the world look to each other for inspiration. The work of Iceland’s people in crowdsourcing a constitution has inspired millions. The resistance of Iceland’s parliament has puzzled many more. Thomas Jefferson, drafting America’s Declaration of Independence, spoke of the people’s “unalienable right to alter or abolish” a constitution. In 2016, we should finally amend his words to make the point even clearer: It is the inalienable right of a people to alter, or abolish, or establish a Constitution. At least where the people rule."
      ],
      IS: ["Þegar skoðuð er saga stjórnarskráa um víða veröld kemur í ljós að Bandaríkin skipa þar sérstakan sess. Stjórnarskrá Bandaríkjanna var sú fyrsta sem þjóðin kom sér saman um og samþykkti sérstaklega. Nú hafa Íslendingar bætt um betur og náð stórmerkum áfanga á þessu sviði. Nú hefur þjóð, í fyrsta sinn á sögulegum tímum, samið sér stjórnarskrá með gegnsæjum hætti og samtakamætti, og nýtt til þess tækni sem ekki var til fyrr en á tuttugustu og fyrstu öld. Þó vill svo undarlega til að þessi stjórnarskrá hefur enn ekki öðlast gildi.",
        "Flestum er í fersku minni að eftir fjármálakreppu ársins 2008 hófu íslenskir ríkisborgarar einstakt ferli til þess að endurheimta fullveldi sitt. Eitt þúsund ríkisborgarar voru valdir með slembiúrtaki og komu sér saman um grunngildin sem vert væri að standa um, og svo var farið að semja stjórnarskrá með frjálsri þátttöku þeirra borgara sem vildu taka þátt. Að frumkvæði Alþingis var förinni haldið áfram með því að mæla fyrir um kosningu til sérstaks stjórnlagaþings. ",
        "Ríflega fimm hundruð einstaklingar buðu sig fram til þess að sitja á þessu 25 manna þingi sem síðar varð stjórnlagaráð. Fundahöld stóðu yfir í liðlega fjóra mánuði og voru verk stjórnlagaráðs jafnan birt almenningi, jafnframt því sem auglýst var eftir athugasemdum og tillögum frá borgurunum. Almenningur lagði fram liðlega 3.600 athugasemdir, og leiddu þær til ótal breytinga. Lokadrög voru samþykkt einróma af öllum fulltrúum stjórnlagaráðs og loks lögð fyrir þingið og þjóðina. Um tveir þriðju kjósenda sögðust vilja þessi drög sem grundvöll að nýrri stjórnarskrá.",
        "Aldrei hafði neitt þessu líkt gerst í sögu stjórnarskrárréttar. Ef lýðræði er vald þjóðar, og ef fullveldi lýðræðisþjóðar byggist á vilja þjóðarinnar, þá er þessi aðferð og þessi stjórnarskrá eins gild og ósvikin og stjórnarskrár annarra ríkja heimsins. Þó hefur Alþingi hafnað því að þessi stjórnarskrá skuli öðlast gildi. Þá kviknar spurning sem hver og einn sem berst fyrir lýðræði um heimsbyggð alla hlýtur að spyrja sig: með hvaða rétti?",
        "Við gerð stjórnarskrárinnar var vissulega gert ráð fyrir því að hún yrði að lokum lögð fyrir Alþingi til samþykktar, rétt eins og drottningin leggur blessun sína yfir skipun ríkisstjórnar Breta. Drottningunni er hins vegar ljóst að valdið sem fylgir þessum rétti hlýtur að vera takmarkað, ef Bretar eiga að teljast lýðræðisþjóðfélag. Sama á við um Ísland. Þegar þjóðin hefur lokið við stórvirki á borð við þetta, samið stjórnarskrá á víðtækari og opnari hátt en nokkur dæmi eru um í sögu stjórnskipunarréttar og fengið verkið staðfest með niðurstöðu ráðgefandi þjóðaratkvæðagreiðslu, hefur þá Alþingi nokkurt siðferðislegt vald til þess að hafna henni?",
        "Vitaskuld eru ekki allir jafnhrifnir af öllu sem þar er að finna, enda er lýðræði ekki fyrirheit um fullkomleika, og engin stjórnarskrá hefur nokkru sinni vakið óskipta hrifningu allra, sem hún varðar. Nægir þar að nefna dæmið um frelsi einnar milljónar afrískra þræla, þegar Bandaríkjamenn samþykktu stjórnarskrá 1808, en það frelsi braut í bága við stjórnarskrána.",
        "Að því er Ísland varðar mætti spyrja hverjum fullveldið tilheyri. Er þjóðin fullvalda eða er hún það ekki? Ef þjóðin er fullvalda, krefst hún þess þá ekki að vilji hennar sé virtur?",
        "Þetta er vitaskuld spurning sem varðar Íslendinga, en líka heimsbyggð alla. Fullveldishugtakið hefur þróast í tímans rás. Það var hjá guði, hjá konungi, hjá elítu, og loks hjá þjóðinni. Þjóðir heims líta hver til annarrar í leit að hugmyndum. Afrek íslensku þjóðarinnar, sem samdi stjórnarskrá með opinni og gegnsærri aðferð, hefur veitt milljónum manna innblástur. Þeir eru þó mun fleiri sem furða sig á andstöðu Alþingis. Þegar Thomas Jefferson var að semja sjálfstæðisyfirlýsingu Bandaríkjanna talaði hann um „óafturkræfan rétt þjóðar til þess að breyta eða ógilda“ stjórnarskrá. Á því herrans ári 2016 ber okkur að breyta orðum hans til þess að hnykkja á því sem máli skiptir: Það er óafturkræfur réttur þjóðar að breyta, eða ógilda, eða semja stjórnarskrá, að minnsta kosti þar sem valdið er hjá þjóðinni."
      ],
    }
  }, {
    title: {
      EN: "Democracy in the balance",
      IS: "Í húfi er lýðræðið",
    },
    languages: ["EN", "IS"],
    author: "Marc Fleurbaey",
    translator: 'Ólöf Pétursdóttir',
    authorPics: ["/img/authors/fleurbaey.png"],
    authorBios: {
      EN: [
        "Dr. Marc Fleurbaey Professor in Economics and Humanistic Studies, Public Affairs and the University Center for Human Values Princeton University"
      ],
      IS: ["Dr. Marc Fleurbaey hagfræðiprófessor við Princeton háskóla."],
    },
    text: {
      EN: [
        "Iceland is a very interesting country. With its small population, it can, more easily than larger countries, experiment and innovate in social organization. For instance, it has held its bankers liable for what happened in 2008, while no other country had the courage to do so.",
        "The constitutional draft written in 2012 is another impressive and innovative achievement. Coming out of a bottom-up process involving a large citizen forum defining the key values of the country and an election of a smaller council which proceeded in a remarkably open way, it is a unique blend of popular wisdom and expertise. And perhaps that is why it has stalled in the parliamentary process.",
        "What is at stake? Perhaps, the very essence of democracy. There are two conceptions of democracy. The conception that dominates in usual public discourse about the “democratic countries” was theorized by the Austrian-American economist Joseph Schumpeter, for instance. It sees democracy in institutions that allow for competition in public offices, with a system of elections from which few normally able adult citizens are excluded. Some countries are less democratic than others when they erect barriers that make it difficult for voters to access the polling stations, “gerrymander” districts to engineer artificial majorities, or exclude some political groups from the competition on dubious grounds. But, according to this conception, an open and fraudless electoral system is enough to have a thriving democracy.",
        "There is, however, another conception of democracy that is generally supported by popular wisdom. It does not see democracy in political competition but in the possibility for everyone to have a say in the decisions that affect one’s life, in all domains and not just in the general political decisions. According to this more demanding conception, democracy is lacking when the key economic and political decisions affecting the lives of citizens are influenced by unelected elites and lobbyists, when the media are controlled by particular interests, or when the funding of political campaigns is a channel of occult influences.",
        "This conception is supported by popular wisdom because everyone wants control over one’s life, and such control is thwarted when power is captured by an oligarchy in the organizations where important decisions are made. This conception of democracy is completely in line with the ongoing push for the empowerment of women in the family and in society at large, for the empowerment of stakeholders in corporate governance, and for a greater control of citizens over economic and social affairs.",
        "Which brings us back to the Icelandic constitutional draft. The way in which it was drafted, with open participation by many citizens, is itself a vibrant expression of the philosophy of participative democracy. Moreover, its text also pushes in the same direction. It characteristically does not just sanction basic human rights and basic parliamentary institutions. It also requires transparency in media ownership and political funding, publicity of public administration proceedings, it asserts “the right to an adequate standard of living and social security,” access to health care and education, it imposes constraints on the appropriation and exploitation of natural resources to preserve public interest and protect future generations, it regulates conflicts of interests in parliament. All these provisions can be read as promoting the citizens’ ability to have a greater control over their lives, their private and their common interests. Is this what the incumbent class of politicians is afraid of?"
      ],
      IS: [
        "Ísland er býsna áhugavert land. Íbúar eru þar fáir og því er þar hægara um vik en í fjölmennari ríkjum að gera tilraunir að því er varðar samfélagsgerð, og brydda upp á nýjungum. Þar voru til dæmis stjórnendur bankastofnana kallaðir til ábyrgðar vegna þess sem gerðist árið 2008, en í öðrum löndum höfðu menn ekki kjark til þess.",
        "Stjórnarskrárdrögin sem samin voru 2012 eru annað merkilegt og byltingarkennt afrek. Í því ferli var grasrótin lögð til grundvallar og kallaðir voru saman fjölmargir borgarar á þjóðfundi sem skilgreindu grunngildi þjóðarinnar. Síðan var kjörin fámennari nefnd sem hélt áfram að vinna við verkefnið með fáséðu gagnsæi. Árangurinn er einstök blanda alþýðlegrar visku og sérfræðiþekkingar. Kannski er það þess vegna sem umrædd stjórnarskrá komst ekki í gegnum þingið.",
        "Hvað er í húfi? Ef til vill er það sjálft lýðræðið í innsta eðli sínu. Til er tvenns konar skilningur á hugtakinu lýðræði. Annars vegar er sá sem mest ber á í almennri umræðu um „lýðræðisríki“, en hann er meðal annars fenginn hjá austurrísk-bandaríska hagfræðingnum Joseph Schumpeter. Þar er litið til lýðræðis í stofnunum, þar sem gert er ráð fyrir því að keppt sé um opinberar stöður, og kosningakerfi með þátttöku flestra hæfra einstaklinga. Í sumum ríkjum er minna lýðræði en í öðrum, þar sem kjósendum er gert erfitt um vik að komast á kjörstað, mörk kjördæma eru færð til í því skyni að skapa þannig tiltekinn meirihluta, eða útiloka tiltekin pólitísk samtök frá þátttöku á vafasömum grunni. Í stuttu máli byggist þessi skilningur lýðræðis á því að opið og gagnsætt kosningakerfi nægi til að lýðræði dafni.",
        "Þá er til annar skilningur á lýðræði, sem alþýðuviska staðfestir yfirleitt. Þar er ekki litið á lýðræði sem pólitíska samkeppni, heldur sem möguleika allra til þess að taka þátt í ákvörðunum sem hafa áhrif á líf manna, á öllum sviðum, og ekki aðeins að því er varðar stjórnmál í þröngum skilningi. Samkvæmt þessum skilningi, sem vissulega gerir meiri kröfur, er lýðræði ábótavant þegar lykilákvarðanir, sem hafa áhrif á líf ríkisborgaranna, mótast af elítum sem ekki eru kosnar, og þrýstihópum. Í þessu tilviki eru það sérhagsmunahópar, sem stjórna fjölmiðlunum, og oft er kosningabarátta fjármögnuð eftir leynilegum leiðum.",
        "Þessi skilningur nær hljómgrunni í alþýðuvisku, þar sem allir vilja hafa stjórn á eigin lífi, og slík stjórn er útilokuð þegar fámennisstjórn nær völdum þar sem mikilvægar ákvarðanir eru teknar. Þessi skilningur á lýðræðishugtakinu er í fullkomnu samræmi við aukna þátttöku kvenna í valdastólum, bæði innan fjölskyldunnar og í samfélaginu, valdatöku hagsmunaaðila við stjórn fyrirtækja, og aukna stjórn borgara að því er varðar efnahags- og félagsmál.",
        "Ber þátttökulýðræðinu fagurt vitni",
        "Víkur þá sögunni aftur að íslensku stjórnarskrárdrögunum. Þau voru samin með opinni þátttöku fjölda einstaklinga, og ber það eitt þátttökulýðræðinu fagurt vitni. Auk þess stefnir sá texti í sömu átt. Hann kveður ekki aðeins á um grundvallarmannréttindi og grunnstofnanir þingræðis. Þar er líka krafist gagnsæis í eignarhaldi á fjölmiðlum og fjármögnun stjórnmálaflokka, gagnsæi í allri opinberri stjórnsýslu, og þar er líka kveðið á um rétt til mannsæmandi lífs og almannatrygginga, aðgang að heilsugæslu og menntun, þar eru settar skorður á eign og nýtingu náttúruauðlinda til þess að vernda almannahagsmuni og komandi kynslóðir, þar er gert ráð fyrir lausn hagsmunaárekstra á Alþingi. Öll þessi ákvæði er unnt að skilja sem svo, að ríkisborgarar eru hvattir til þess að stjórna lífi sínu í auknum mæli, einnig eigin hagsmunum og sameiginlegum hagsmunum. Er það þetta sem starfandi stjórnmálamenn óttast?"
      ],
    }
  }, {
    title: {
      EN: "Reflecting On Face-To-Face Democracy",
      IS: "Hugleiðing um lýðræði augliti til auglitis",
    },
    languages: ["EN", "IS"],
    author: "Steven Keeler",
    translator: 'Ólöf Pétursdóttir',
    authorPics: ["/img/authors/keeler.png"],
    authorBios: {
      EN: [
        "Steven Keeler Distinguished Service Professor State University of New York (Cayuga Community College)"
      ],
      IS: ["Steven Keeler, heiðursprófessor State University of New York (Cayuga Community College)."],
    },
    text: {
      EN: [
        "To be effective, democracy demands that its citizens participate in governing themselves. In my opinion, that governance must start a very local level; a level that demands that participants meet and face each other. I have observed how this process works for almost my entire life.",
        "The remarkable effort by the people of Iceland to write a new, grassroots constitution is the greatest political tale of the 21st century. 25 Icelandic citizens, not part of any entrenched political power structure, met, argued, cajoled, listened, worked out differences, and finally, crafted an astonishing new constitution. It was a process of “face-to-face democracy” that represents the best of what democracy has to offer as a system of government.",
        "To be clear, I am an American who loves American democracy and the U.S. Constitution that supports it. American democracy is messy, imperfect, and frustrating. At its best it gives me, as a citizen, control over how I choose to be governed. At its worst, it can lead to the uncompromising gridlock that currently seems endemic in the federal government. The U.S. Constitution can seem outdated and its language terribly vague. It’s open to maddening and frustrating degrees of interpretation. Yet, I wouldn’t dream of trading away the rights it gives to me as an individual.",
        "I learned to value the local politics of democracy at an early age. At six years old, I accompanied my father (an election district chairperson) on the streets of Newark, New Jersey, as he knocked on doors to get his neighbors to sign petitions for political candidates. He represented a big city political “machine,” but to him all politics were personal. He engaged each person in conversation, got to know them, and convinced them to give their support. As I campaigned for candidates throughout my life, my success (or failure) came from that same personal contact with potential voters.",
        "I live in upstate New York in a small village. In New York, a village is the smallest governing district. My village government consists of a mayor and two trustees. 200 votes is often sufficient to be elected. The board makes decisions about the village tax rate, snow removal, road and sidewalk repair, trash disposal, and sewer and water systems. All those issues are very real and personal to village residents. To get elected, a board candidate knocks on doors (including mine) and gets to know the people he or she will represent. This system of face-to-face democracy makes government personal and real.",
        "The night I wrote this reflection, I signed a candidate’s petition. We stood on my front porch and discussed everything from the qualifications of local candidates to which of my neighbors was making soup to ward off the recent cold weather spell - all part of the process of face-to-face democracy.",
        "All the things I have described make me feel included in the process of democracy. I feel as if I have a personal stake and a voice in the process of democracy in my village, state and nation.",
        "Clearly the people of Iceland felt their quest for a new constitution needed ownership by its citizens. Their process for selecting the group that wrote the new constitution was undeniably inclusive. Their embracing of new technology and use of social media were revolutionary methods of giving every citizen a voice and personal stake in a new model of democracy.",
        "The people of Iceland deserve our support and our greatest respect for their commitment to creating a new constitution and a new form of face-to-face democracy. Their innovation, dedication, and commitment should be a model for the world."
      ],
      IS: [
        "Ef lýðræðið á að vera virkt krefst það þess að ríkisborgararnir taki þátt í að stjórna sér. Að mínu mati þarf slík stjórnun að hefjast á mjög staðbundnu stigi, þar sem þátttakendur þurfa að hittast augliti til auglitis. Nánast ævilangt hef ég fylgst með því hvernig þetta ferli virkar.",

        "Íslenska þjóðin gerði merkilega tilraun til þess að semja nýja stjórnarskrá út frá grasrótinni, og það er eitthver magnaðasti viðburður sem hefur orðið í stjórnmálasögu tuttugustu og fyrstu aldar. Tuttugu og fimm íslenskir ríkisborgarar, sem ekki tilheyrðu neinu hefðbundnu stjórnmálaafli, hittust, ræddu saman, miðluðu málum, hlustuðu á aðra, unnu úr ágreiningi sín á milli og loks sömdu þeir undursamlega, nýja stjórnarskrá. Þetta ferli er sannkallað „lýðræði augliti til auglitis“ og þar er að finna bestu hugsanlegu beitingu lýðræðis við stjórn ríkis.",

        "Ég tek strax fram að ég er Bandaríkjamaður og mjög hallur undir bandaríska útgáfu lýðræðisins, og stjórnarskrá Bandaríkjanna sem þar er til grundvallar. Mér er ljóst að bandarískt lýðræði er óreiðukennt, ófullkomið og ófullnægjandi. Þegar best lætur veitir það mér sem ríkisborgara möguleika á að velja mér stjórn. Í versta falli getur það leitt til pattstöðu sem virðist nú um stundir einkenna stjórn ríkjasambandsins. Stjórnarskrá Bandaríkjanna kann að virðast úrelt, og orðalagið sem þar er notað ansi óljóst. Þar eru túlkunarmöguleikarnir í senn ótrúlega margir og þvingandi. Þó vildi ég síst af öllu afsala mér þeim réttindum sem þessi stjórnarskrá veitir mér sem einstaklingi.",

        "Staðbundin lýðræðispólítík",

        "Ungur að árum lærði ég að meta staðbundna lýðræðispólitík. Þegar ég var sex ára fylgdi ég föður mínum (sem var formaður bæjarráðs) um götur bæjarins Newark í New Jersey, þar sem hann knúði dyra og reyndi að fá granna sína til þess að skrifa undir stuðningslista við pólitíska frambjóðendur. Hann var fulltrúi stórrar pólitískrar „vélar“, en fyrir honum voru öll stjórnmál persónubundin. Hann gaf sig á tal við hvern og einn, kynntist mönnum og taldi þá á að veita sér stuðning. Í tímans rás vann ég oft við kosningaherferðir, bæði fyrir frambjóðendur og veitti því athygli að velgengni (og ósigur) leiddi alltaf af persónulegum samskiptum við hugsanlega kjósendur.",

        "Ég bý norðarlega í New York-fylki, í litlu þorpi. Í New York er þorpið minnsta stjórnsýslueiningin. Með stjórn þorpsins fer þorpsráð, sem er skipað bæjarstjóra og tveimur bæjarráðsmönnum Oft nægja 200 atkvæði til setu í ráðinu. Ráðið tekur ákvarðanir um útsvar í þorpinu, snjómokstur, sorphirðu, frárennslismál og vatnsveitu. Öll þessi málefni eru mjög áþreifanleg og varða þorpsbúa persónulega. Vilji frambjóðandi til bæjarráðs ná kjöri verður hann að knýja dyra (líka hjá mér) og kynnast þeim sem viðkomandi verður fulltrúi fyrir. Með þessu kerfi lýðræðis augliti til auglitis verður stjórnin mjög persónuleg og áþreifanleg.",

        "Kvöldið áður en ég setti þessar vangaveltur á blað skrifaði ég á undirskriftalista fyrir pólitískan frambjóðanda Við ræddum málin vítt og breitt fyrir utan húsið, um hæfi frambjóðendanna á staðnum og um nágranna minn sem var að elda súpu til þess að verjast kuldakastinu. Allt tilheyrði þetta lýðræði augliti til auglitis.",

        "Allt það sem ég hef lýst veldur því að mér finnst ég vera með í ráðum í lýðræðislegu ferli. Ég finn að ég gæti eigin hagsmuna og að rödd mín heyrist í lýðræðisferlinu í þorpinu heima, í fylkinu og meðal þjóðarinnar.",

        "Það er greinilegt að Íslendingar bjuggu yfir djúpum skilningi á opinberri leit sinni að nýrri stjórnarskrá sem krafðist þess að ríkisborgararnir ættu hana sjálfir. Þeir beittu nýrri tækni samfélagsmiðla, og er það byltingarkennd aðferð til þess að rödd hvers ríkisborgara fái að njóta sín og að allir eigi persónulegra hagsmuna að gæta í nýju lýðræðiskerfi.",

        "Íslenska þjóðin á það skilið að við veitum henni stuðning, og hún verðskuldar skilyrðislausa virðingu okkar fyrir að hafa samið nýja stjórnarskrá og nýja tegund af lýðræði augliti til auglitis. Frumleg hugsun þeirra, eftirfylgni og þrotlaust starf ætti að vera til fyrirmyndar fyrir heimsbyggð alla.",
      ],
    }
  }, {
    title: {
      EN: "Icelandic Spring 2016: Building a democracy for the rest of us",
      IS: "Íslenska vorið 2016: upp rennur lýðræði fyrir okkur öll",
    },
    languages: ["EN", "IS"],
    author: "Dr. Cricket Keating & Dr. Susan Burgess",
    translator: "Ólöf Pétursdóttir",
    authorPics: ["/img/authors/keating.png", "/img/authors/burgess.png"],
    authorBios: {
      EN: [
        "Dr. Cricket Keating, Ohio State University",
        "Dr. Susan Burgess, Ohio University"
      ],
      IS: [
        "Cricket Keating, prófessor í stjórnmálafræðum við Ohio State University í Bandaríkjunum",
        "Susan Burgess, prófessor í stjórnmálafræðum við Ohio State University í Bandaríkjunum.",
      ]
    },
    text: {
      EN: [
        "In the early 2010s, the world’s attention was riveted by what became known as the Arab Spring. Women and men across the Arab world mobilized social media tools such as Facebook and Twitter to organize, document, and publicize their efforts to bring down repressive regimes. Around the same time, Iceland’s experience in crowd-sourcing the Constitution demonstrated that 21 st century social media tools could be used to build a participatory democracy. When faced with the monopolization of decision-making by the elite, Icelandic activists provided alternative platforms for collective decision-making, such as referenda, the “parliament of the streets,” and a people’s national assembly.",
        "Even though decisions that these bodies made were nonbinding, they articulated and publicized the choices that the public made collectively, profoundly challenging older, non-participatory and elite-based forms decision-making. Icelanders opened up spaces that allowed ordinary people to create new visions for the future of their country, combining social media and face-to- face deliberations, creating a new kind of participatory process that eventually became a model for “official” constitution writing that the government later authorized.",
        "Indeed, Iceland’s experiment with digital democracy demonstrates that it is possible to use twenty-first century social media tools to create a new form of participation so that, in the words of the Constitution’s preamble, “everyone has a seat at the same table.” Such a democracy is of, for, and by the 99%, or “the rest of us” as political theorist Jodi Dean so eloquently puts it. It is grounded in a collective norm that insists on having a say in decisions that affect our lives and in the power relations to which we are subject. As one Icelandic participant said, “it can be done, we have shown that.”",
        "Given the specificity of conditions in Iceland-its small, well-educated, ethnically homogenous population, almost all with access to the internet-some skeptics have questioned whether Iceland’s constitutional innovations can be replicated in deeply stratified, multi-ethnic, multi-lingual contexts with larger populations such as the United States or India.  That question is an open one, of course, but we would like to note that small countries have often taken the lead in extending and deepening democratic practice.",
        "For example, in 1893, New Zealand became the first country to implement universal adult suffrage, paving the way for a practice that is now an accepted-if not fully realized-democratic norm.  Now, Iceland is showing the world how to democratize democracy once again, using twenty-first century technologies to create new norms of participation that take constitutional democracy to the next level. Unfortunately, the Icelandic parliament has not voted on the Constitution, ignoring the 2012 referendum in which more than 2/3 or Icelanders voted to approve it.",
        "Spring 2016 brings to Icelanders an opportunity to lead a resurgence of energy and optimism for the possibility of democratic change. Building on the momentum generated by the success of the people’s protests that recently led the Prime Minister to resign, activists are pressuring Parliament to vote on the Constitution at last. In late May, Icelanders will reconvene the parliament of the streets to re-present the Constitution to the Parliament. In good participatory form, this will be accompanied by days of collective analysis and dialogue about the constitution itself. In the words of one Icelandic activist, “Even though we are a very tiny island, we can have a role to play in the world... ; Iceland is kind of like a laboratory, it’s a laboratory for a kind of a new world model... What we are doing with grassroots, with crowd-sourcing our vision and our values... ;  is a kind of a new development of democracy.” From across the ocean, we join you in hope and struggle to bring this new form of democracy to fruition at last: a democracy for the rest of us."
      ],
      IS: [
        "Upp úr 2010 fylgdist heimsbyggð öll með því sem síðar var kallað arabíska vorið. Konur og karlar í arabalöndunum virkjuðu samfélagsmiðla á borð við Facebook og Twitter til að skipuleggja, skrásetja og opinbera viðleitni sína til þess að losna undan harðstjórn. Um sama leyti var almenningur á Íslandi virkjaður til að semja stjórnarskrá og þar með var sýnt fram á að unnt væri að nota fjölmiðlunartæki tuttugustu og fyrstu aldar til þess að skapa þátttökulýðræði.",
        "Íslendingar brugðust við einokun elítunnar á ákvarðanatöku með því að leggja nýjan vettvang til sameiginlegrar ákvarðanatöku almennings, með þjóðfundum, stjórnlagaþingi og loks þjóðaratkvæðagreiðslu um nýja stjórnarskrá.",
        "Reyndar voru ákvarðanir þessara aðila ekki bindandi, en þar var sett fram og kynnt sameiginlegt val almennings, og var þar með vefengdur með afgerandi hætti hefðbundinn ákvörðunarréttur elítunnar. Íslendingar luku upp rými sem gerði almenningi kleift að skapa nýja framtíðarsýn fyrir landið, með samspili samfélagsmiðla og opinna umræðna, og þar með varð til ný tegund þátttökuferlis sem varð að fyrirmynd fyrir „opinbera“ ritun stjórnarskrár, og var það gert með leyfi stjórnarinnar.",
        "Það eru orð að sönnu að tilraun Íslendinga til stafræns lýðræðis sannar að það er unnt að beita samfélagsmiðlum tuttugustu og fyrstu aldar til þess að brydda upp á nýjum aðferðum til þátttöku, þannig að allir sitji „við sama borð“, eins og það er orðað í formála nýju stjórnarskrárinnar. Slíkt lýðræði er gert af og fyrir 99%, eða „okkur hin“, eins og stjórnmálafræðingurinn Jodi Dean orðaði það svo skýrt. Það er byggt á sameiginlegum staðli þar sem gerð er krafa um að við komum að ákvörðunum sem hafa áhrif á líf okkar, og að því valdi sem við lútum. Eins og íslenskur þátttakandi orðaði það: „Það er hægt, við sýndum fram á það.“",
        "Tækifæri til að leiða nýtt átak",
        "Á Íslandi eru aðstæður nokkuð sérstakar. Þjóðin er fámenn, menntuð og einsleit, og nánast allir hafa aðgang að Netinu. Því hafa ýmsir dregið í efa að nýjungar sem Íslendingar hafa lagt fram í stjórnarskrármálum geti nýst í lagskiptu, fjölþjóðlegu, fjöltyngdu og fjölmennu samfélagi á borð við Bandaríkin eða Indland. Auðvitað er spurningunni ósvarað, en við viljum benda á að lítil ríki hafa oft haft forgöngu um að breikka og dýpka framkvæmd lýðræðis. Til dæmis var Nýja-Sjáland fyrsta ríkið, þar sem almennur kosningaréttur fullorðinna var tekinn upp árið 1893, og nú þykir það sjálfsagt í lýðræðisríki, þótt slíkur kosningaréttur hafi ekki alls staðar verið tekinn upp. Nú vísa Íslendingar heimsbyggðinni veginn að lýðræðisvæddu lýðræði, með nýtingu hátæknitækja tuttugustu og fyrstu aldar, þannig að nýjar hugmyndir um þátttöku almennings komast í framkvæmd og færa stjórnarskrárbundið lýðræði upp í æðra veldi. Því miður hefur Alþingi ekki fullgilt stjórnarskrána og hunsað ráðgefandi þjóðaratkvæðagreiðsluna 2012, þar sem um tveir af hverjum þremur kjósendum samþykktu hana.",
        "Vorið 2016 færir Íslendingum tækifæri til að leiða nýtt átak og von um lýðræðislegar breytingar. Kraftvægi skapaðist þegar forsætisráðherra sagði af sér í kjölfar mótmæla, og nú þrýsta aðgerða­sinnar á Alþingi til þess að fullgilda stjórnarskrána eftir öll þessi ár. Í maílok verður haldinn opinn borgarafundur um framtíð lýðræðis og stjórnarskrána. Eins og vera ber þegar þátttaka er almenn verður þessu vonandi fylgt eftir með nokkurra daga almennri greiningu stöðunnar og samræðum um sjálfa stjórnarskrána. Eins og einn Íslendinganna orðaði það: „Við erum bara lítið eyland en við höfum hlutverki að gegna í heimssögunni. Ísland er eins og tilraunastofa, það er tilraunastofa fyrir nýja heimsmynd?… Það sem við gerum í grasrótinni, með því að veita öllum aðild að hugsjónum okkar og gildum?… það er nýjung í þróun lýðræðis.“ Við sendum ykkur kveðju yfir Atlantsála og sameinumst ykkur í von og baráttu um að þessi nýja mynd lýðræðis verði loks að veruleika: lýðræði fyrir okkur öll."
      ],
    }
  }, {
    title: {
      EN: "People of Iceland: make it work",
      IS: "Íslendingar, það skal takast",
    },
    languages: ["EN"],
    author: "Brandon V. Stracener, Stephen M. Duvernay, & David A. Carrillo",
    translator: 'Ólöf Pétursdóttir',
    authorPics: ["/img/authors/carrillo.jpg", "/img/authors/duvernay.jpg",
      "/img/authors/stracener.jpg"
    ],
    authorBios: {
      EN: [
        "David A. Carrillo, executive director, California Constitution Center",
        "Stephen M. Duvernay, Senior research fellow, California Constitution Center",
        "Brandon V. Stracener, research fellow, California Constitution Center"
      ],
      IS: [
        "David A. Carrillo, sérfræðingur í California Constitution Center, Berkeley School of Law University",
        "Stephen M. Duvernay, sérfræðingur í California Constitution Center, Berkeley School of Law University",
        "Brandon V. Stracener, sérfræðingur í California Constitution Center, Berkeley School of Law University"
      ]
    },
    text: {
      EN: [
        "Iceland has a unique opportunity to remake its government. Its people, acting in concert with Parliament and through a Constitutional Council, prepared a revised constitution. The people approved the draft, then made a simple request to their elected representatives: hold a vote. Accept our reforms or reject them. Yet for over three years, Parliament has failed to act. What now?",
        "In the United States, we believe that ours is a government “of the people, by the people, for the people.” The fundamental principle of a representative republic is that the people grant a government its powers, to be exercised for the people’s benefit. Central to this view is the people’s right to alter or reform their government when it ceases to serve their needs-this is the essence of popular sovereignty. The people created the government; it exists for their benefit; and the people retain the power to remake it. Indeed, the California constitution expressly reserves that power to the people and describes a process for reforming the existing government. Using the prescribed constitutional revision process is the first remedy for an unsound government. This the people of Iceland have attempted, to no avail. That is not the end of the matter. Instead, the next remedy is to redouble the reform effort by using all of a republic’s traditional tools and liberties: speak out, publish, assemble, and demand action from parliament. They are your agents-instruct them. Note which members stand against reform, and vote them out in the next election. Run against them. Have faith-history has demonstrated the durability of democratic institutions bent on popular self-government. If the people want freedom, they can win it.",
        "History offers a different lesson for governments that prevent the people from accomplishing their ends. Iceland’s Parliament should listen carefully to its electorate. When the democratic process collapses, and a government breaks faith with its citizens by acting for its own preservation rather than in the people’s best interest, only the ultimate remedy remains: popular revolt. This is a hard-learned lesson in the United States, a nation twice-born of revolution. The Declaration of Independence is a revolutionary manifesto: whenever government “becomes destructive” of the ends of “Life, Liberty and the pursuit of Happiness,” it is the people’s right “to institute new Government.” And our President Abraham Lincoln was blunt when facing another great constitutional crisis: “Whenever [the people] shall grow weary of the existing government, they can exercise their constitutional right of amending it, or their revolutionary right to dismember or overthrow it.” America’s founding and our Civil War teach that citizens must take responsibility for managing their government, and for remaking failed institutions.",
        "Iceland faces a stark choice between reform either through legal processes, or by other means. To be clear, we do not advocate the use of force. American history is characterized by negotiation through armed conflict, and it has not always gone well for us; here the United States may be more a cautionary tale than an example to follow. But there is no dispute that Iceland’s people have only three courses of action. (We do not view giving up as an option.) It is by now clear that the first remedy (popular constitutional reform) has proved futile. The ultimate remedy-revolution-is extreme. Thus, an aggressive campaign pursuing the second remedy is the best course. Vote out uncooperative members of government. Run against them. Replace them with representatives who understand that government receives its power from the people. It is said that every nation gets the government it deserves. If you want a good government in Iceland, you have to earn it.",
      ],
      IS: [
        "Nú veitist Íslandi einstakt tækifæri til að endurskapa eigin stjórnarhætti. Þjóðin tók höndum saman við Alþingi og samdi endurskoðaða stjórnarskrá með tilstuðlan Stjórnlagaráðs. Þjóðin samþykkti að leggja skyldi þau stjórnarskrárdrög til grundvallar og beindi til kjörinna fulltrúa einfaldri beiðni um að greiða atkvæði um þau, samþykkja umbæturnar eða hafna þeim. Síðan eru liðin yfir þrjú ár og Alþingi hefur ekkert gert. Hvað er framundan?",
        "Í Bandaríkjunum trúum við því að stjórnin sé stjórn þjóðarinnar, á vegum þjóðarinnar, fyrir þjóðina. Það er grundvallaratriði í fulltrúalýðveldi að þjóðin feli stjórninni völd og að þeim sé beitt í þágu þjóðarinnar. Í þessu viðhorfi felst að þjóðin eigi rétt á að breyta eða bæta stjórnina þegar stjórnin hættir að þjóna tilgangi sínum. Það er kjarninn í fullveldi þjóðar. Þjóðin skóp stjórnina, stjórnin starfar í þágu þjóðar, og þjóðin hefur vald til að endurskapa hana. Reyndar er skýrt ákvæði í stjórnarskrá Kaliforníu, þar sem þessi réttur þjóðarinnar er áskilinn, og þar er skilgreint verkferli til endurbóta á sitjandi stjórn.",
        "Endurskoðun stjórnarskrár eins og mælt er fyrir um hana er fyrsta úrræðið sem má beita við óheilbrigðri stjórn. Þetta hefur íslenska þjóðin reynt án árangurs. Þar með er ekki öllu lokið. Næsta úrræði er að reyna áfram að knýja fram endurbætur og beita þá öllum hefðbundnum ráðum og ferlum sem felast í lýðræði. Tjáið ykkur, birtið skrif ykkar, komið saman og krefjist aðgerða af hálfu þingmanna. Þeir eru í þjónustu ykkar, gefið þeim fyrirmæli. Takið eftir því hverjir leggjast gegn endurbótum og útilokið þá við næstu kosningar. Bjóðið ykkur fram gegn þeim. Missið ekki móðinn, sagan hefur sýnt fram á varanleika lýðræðislegra stofnana undir stjórn þjóðarinnar. Vilji þjóðin frelsi getur hún öðlast það.",
        "Þingmenn hlusti á kjósendur",
        "Sagan birtir okkur annan veruleika varðandi stjórnir sem vilja koma í veg fyrir að þjóðin nái markmiði sínu. Íslenskum þingmönnum væri best að hlusta vel eftir því sem kjósendur segja. Þegar framkvæmd lýðræðisins hrynur og ríkisstjórn brýtur trúnað við borgarana og vinnur að því að sitja sem lengst, en hunsar hagsmuni þjóðarinnar er aðeins eitt úrræði eftir: uppreisn þjóðarinnar.",
        "Þessi lærdómur hefur Bandaríkjamönnum verið dýrkeyptur, þar fer þjóð sem hefur tvívegis endurfæðst eftir byltingu. Sjálfstæðisyfirlýsingin er stefnuyfirlýsing byltingarsinna: þegar stjórnvöld reynast skaðleg því takmarki sem felst í „lífi, frelsi og hamingjuleit“ er það réttur þjóðarinnar að „koma á nýrri stjórn“. Forseti vor, Abraham Lincoln, talaði tæpitungulaust þegar stjórnarskrárkreppa blasti við: „Þegar [þjóðin] þreytist á sitjandi ríkisstjórn getur hún beitt stjórnarskrárbundnum rétti sínum til að breyta henni, eða rétti sínum til byltingar með því að leysa hana upp eða steypa henni.“ Stofnun Bandaríkjanna og borgarastyrjöldin eru til marks um að borgurum beri að axla ábyrgð á að stýra stjórn sinni og endurreisa fallnar stofnanir lýðræðisins.",
        "Á Íslandi er aðeins um tvo kosti að velja: annaðhvort þarf að bæta stjórnarhætti eftir löglegum leiðum, eða eftir öðrum leiðum. Við viljum taka skýrt fram að við erum ekki fylgjandi því að valdi sé beitt. Saga Bandaríkjanna einkennist af því að vopnin hafa verið látin tala, og það hefur ekki alltaf gefið góða raun. Hér eru dæmin frá Bandaríkjunum fremur víti til varnaðar en æskileg fyrirmynd. Það liggur ljóst fyrir að íslenska þjóðin á aðeins þriggja kosta völ. (Við lítum ekki á uppgjöf sem valkost.) Nú er komið á daginn að fyrsta ráðið (stjórnarskrárbætur af hálfu þjóðarinnar) hefur reynst gagnslaust. Síðasta úrræðið, bylting, er örþrifaráð. Þess vegna væri best að beita öðru ráðinu með ágengum hætti. Kjósið ekki aftur þá stjórnarliða sem hafna samvinnu. Bjóðið ykkur fram gegn þeim. Skiptið þeim út fyrir fulltrúa sem skilja að stjórnin þiggur vald sitt frá þjóðinni. Sagt er að hver þjóð kjósi sér þá stjórn sem hún á skilið. Vilji menn góða stjórn á Íslandi verða þeir að vinna fyrir henni."
      ],
    }
  }, {
    title: {
      EN: "The next Step in Iceland?",
      IS: "Hvert verður næsta skrefið á Íslandi?",
    },
    languages: ["EN", "IS"],
    author: "Delia Popescu",
    translator: "Ólöf Pétursdóttir",
    authorPics: ["/img/authors/popescu.png"],
    authorBios: {
      EN: ["Dr. Delia Popescu Chair of Political Science Lemoyne College, New York"],
      IS: ["Delia Popescu, doktor í stjórnmálafræði og deildarstjóri við Lemoyne College í New York fylki."]
    },
    text: {
      EN: [
        "Iceland did something about the 2008 economic collapse that few other countries even dream of: it reconsidered its values. In a uniquely pragmatic assessment of how the working principles of a political system allowed for political behavior that brought Iceland to the brink of collapse, Icelandic citizens decided it was time to see their values enshrined into a new Constitution to reorient their own political system. Yet the Parliament refuses to consider this grassroots constitutional change.",
        "Faced with a democratic process without precedent in constitutional history, the Icelandic Parliament is unmoved by the call of its people. What is under debate here is the essence of democracy itself, from the perspective of values and process. Democratic values have to do, at their core, with broad participation open equally to all stakeholders. The test of popular participation has been passed in Iceland: the grassroots efforts led to the random selection of 1500 citizens who were asked to define core values. More than 500 argued for the chance to participate in a drafting commission with 25 seats. The openness of the process is unprecedented in the history of constitutional change. The drafts were not only the work of broadly selected representative voices, but they also benefited from the input of no less than 3600 comments, and garnered the support of 2/3 of the population. The democratic test has been passed with flying colors and Iceland can now boast a uniquely modern and democratic “crowdsourced” constitutional process that stands as a model to the rest of the world. The legality test has also been passed: Parliament itself established the procedure to select those participating in the drafting of the document. Yet when the constitutional document was finally completed, the Icelandic Parliament, instead of celebrating its historical breakthrough, chose to table it for three long years.",
        "So what is the next step in Iceland? One option would be to wait. An advocate of the constitutional reform noted that this Parliament won't be the last. Democracy is also about vetting and procedure, and politicians can be voted out of office. But this approach requires waiting for the next election round and fighting the fight at that time, while ignoring the fact that the voice of the demos has already spoken. Waiting for what is seemingly a democratic process is sometimes undemocratic, especially when the voice of the people itself is deferred. It is perhaps procedurally pragmatic to wait, but it dents a hierarchy of democratic values in which the people should come first and not second to political elites and interests. Iceland should not put its democracy on ice.",
        "As an Eastern European formed by the spirit of Vaclav Havel’s “power of the powerless,” I cannot help but think that this is a time for renewed opposition and nonviolent protest. Nonviolence works and it is particularly democratic. The voice of democratic pressure can take a variety of forms, many of which I already see happening: discussions, gatherings, letters, responses, but much more can be done to symbolically colonize the political space. Opposition in public spaces, performed through anything from marches across the country, sit-ins around government buildings, to public music, theatrical performance, and poetry readings have a long tradition of healthy political disruption. The ritual of creative protest can complete the cycle of the “Kitchenware revolution” by restaging the political fight in symbolic, nonviolent terms. As Havel would tell us, it is the environment of power that needs changing, and it is disruption that changes political minds."
      ],
      IS: [
        "Íslendingar brugðust við efnhagshruninu 2008 með þeim hætti sem fáar aðrar þjóðir hafa látið sér detta í hug: þeir tóku eigið gildismat til endurskoðunar. Þá fór fram einstaklega raunsæislegt mat á því hvernig starfshættirnir í stjórnkerfi brugðust, þannig að stjórnmálaöfl leiddu Ísland nánast til glötunar. Íslendingar ákváðu að nú væri tímabært að festa gildismat sitt í nýrri stjórnarskrá, sem yrði leiðarljós stjórnkerfis þeirra. Þó neitar Alþingi að taka þessa stjórnarskrá grasrótarinnar til greina. Alþingi stendur frammi fyrir lýðræðislegum viðburði, sem á sér ekki hliðstæðu í stjórnarskrársögu, en sinnir þó ekki ákalli þjóðarinnar.",
        "Hér er sjálft frumefni lýðræðis í húfi, að því er varðar gildismat og aðferðarfræði. Í raun snýst lýðræðislegt gildismat um víðtæka þátttöku, sem öllum er opin, hagsmunaaðilum jafnt sem öðrum. Ísland hefur staðist prófið að því er varðar þátttöku almennings: átak grasrótarinnar leiddi til slembiúrtaks 1000 ríkisborgara, sem voru beðnir um að skilgreina gildismat sitt. Ríflega 500 manns vildu taka þátt í starfi 25 manna stjórnlagaráðs. Svo opið ferli er áður óþekkt í sögu stjórnarskrárbreytinga. Drögin voru verk fulltrúa mjög breiðs fjölda, og þau styrktust af ríflega 3600 athugasemdum, enda nutu þau stuðnings tveggja kjósenda af hverjum þremur í ráðgefandi þjóðaratkvæðagreiðslu.",
        "Íslenska þjóðin stóðst lýðræðisprófið með sóma og getur nú státað af einstaklega nútímalegu og lýðræðislegu stjórnarskrárferli, þar sem almenningur lagði hönd á plóginn, og er þetta öðrum þjóðum til eftirbreytni. Íslendingar stóðust einnig lögmætisprófið: Alþingi ákvarðaði sjálft aðferðina við að velja þátttakendur í gerð stjórnarskrárdraga. Þó fór svo, að þegar vinnu við það skjal var loks lokið fagnaði Alþingi ekki sögulegum viðburði, heldur kaus þess í stað að leggja stjórnarskrárdrögin í salt, þar sem þau hafa legið um þriggja ára skeið.",
        "Hvað tekur nú við á Íslandi? Einn valkosturinn væri að bíða enn um hríð. Einn talsmanna nýju stjórnarskrárinnar benti á að annað Alþingi tæki við af því sem nú situr. Lýðræðið snýst einnig um neitunarvald og starfsreglur, og hægt er að hætta að kjósa tiltekna stjórnmálamenn. Þessi nálgun krefst þess að beðið sé næstu kosninga og áfram verði barist, jafnframt sem litið yrði hjá því að almenningur hefur þegar tjáð sig með mótmælum. Stundum er ekki lýðræðislegt að bíða eftir því sem við fyrstu sýn virðist lýðræðislegt, sérstaklega þegar rödd þjóðarinnar er sniðgengin. Kannski er biðin réttur valkostur út frá stjórnsýslulegum sjónarhóli, en hún leysir upp lýðræðislega forgangsröðun, þar sem þjóðin á að vera í fyrsta sæti, en ekki næst á eftir elítunni og hagsmunahópunum. Íslendingar eiga ekki að leggja lýðræðið í salt.",
        "Ég er frá Austur-Evrópu og mótaðist af anda Vaclav Havels sem vildi færa valdið til valdalausra, og ég get ekki varist þeirri hugsun að nú sé tími til þess að staðfesta andspyrnuna enn frekar og efna til mótmæla án ofbeldis. Ofbeldisleysi virkar og er sérstaklega lýðræðislegt. Rödd lýðræðislegs þrýstings getur tekið á sig margar myndir, og hef ég orðið vitni að mörgum þeirra: samræður, fundir, bréfaskriftir, svör, og enn má gera betur til þess að leggja undir sig vettvang stjórnmála á táknrænan hátt. Andspyrna á opinberum stöðum, göngur um allt land, þrásetur í kringum opinberar byggingar, opinber tónlistarflutningur, leiksýningar og ljóðalestur, fyrir þessu öllu er löng hefð í heilbrigðum, pólitískum mótmælum. Reglubundin og skapandi mótmæli geta lokið ferli búsáhaldabyltingarinnar með því að sviðsetja valdabaráttuna á táknrænan hátt og án ofbeldis. Eins og Havel sagði er það valdumhverfið sem þarf að breytast, og það er upplausn þess umhverfis sem getur breytt hugarfari stjórnmálamanna."
      ],
    }
  }, {
    title: {
      EN: "For a democratic way forward: The new Icelandic constitution is important for Europe (and the rest of the world)",
      IS: "Ný stjórnarskrá Íslands skiptir miklu máli fyrir Evrópu (og heimsbyggð alla)",
    },
    languages: ["EN", "IS"],
    author: "Arne Hintz",
    translator: "Ólöf Pétursdóttir",
    authorPics: ["/img/authors/hintz.png"],
    authorBios: {
      EN: [
        "Arne Hintz is Senior Lecturer at Cardiff University, UK, where he chairs the Research Group Digital Media and Society, directs an MA programme of the same title, and leads the research project ‘Digital Citizenship and Surveillance Society’"
      ],
      IS: [
        "Arne Hintz, blaðamaður og doktor í stjórnmálafræði, kennari við Cardiff háskóla í Bretlandi."
      ]
    },
    text: {
      EN: [
        "As the UK is approaching its referendum on leaving the European Union, advocating for continued EU membership has rarely been more difficult. The continent is trapped in a permanent financial crisis, the far right is on the rise in many countries, and the borders that seemed to belong to the past are re-erected. Serious doubts about solidarity and power relations in the EU have been raised, particularly, about the way the Greek government was forced to implement austerity measures that contradicted the will of the people and have been called unsustainable even by the International Monetary Fund (IMF). The Twitter hashtag #thisisacoup which was trending after the temporary settlement of the EU-Greece conflict in June last year demonstrates the worrying situation of democracy in Europe.",
        "Yet the case in favour of ‘Brexit’ (the exit of the UK from the EU) hardly seems more convincing. Living conditions for the majority of people living in the UK are deteriorating with every new wave of austerity measures, and government programmes for tackling ‘extremism’ have put a chilling effect on pluralistic democratic discourse. With the new ‘Investigatory Powers Bill’ which is likely to be adopted later this year, the mass surveillance powers criticised in the Snowden revelations are expanded and codified in law.",
        "Times of economic crisis and terrorist fears do not seem to offer ideal conditions for strengthening democracy. And yet these are exactly the times when broader discussion, public debate, innovative and inclusive solutions and actual change would be necessary. This is why it has been so inspiring for many people to look at Iceland. There the financial crisis led to significant political and economic change. Policy reform proposals such as the Icelandic Modern Media Initiative (IMMI) suggested comprehensive new development models for the country, and a new constitution was created through an open and inclusive grassroots process - by the people for the people. A commission of Icelandic citizens drafted the text, several thousand comments were offered by the public, and a referendum adopted the final outcome.",
        "People in Iceland have thereby chosen a distinctly democratic path out of the crisis and towards a better future. They have demonstrated that the uninspired stasis of current European politics, mixed with authoritarian and exclusionary tendencies, is not the only possible reaction to security threats and economic hardships. On the contrary, they show that democracy is alive - even, and especially, in times like these - and that we as people are able to create new foundations for how we want the state to look and how we want our lives to be."
      ],
      IS: [
        "Frá sjónarhóli Evrópubúa er Ísland tákn lýðræðis og framfara, nú þegar heimsálfan er nánast öll þjökuð af efnahagslegri óvissu, einræðistilburðum og ótta. Ný stjórnarskrá Íslands, stjórnarskrá þjóðarinnar, vísar heimsbyggðinni leið út úr kreppunni og til nýrrar uppbyggingar. Brýnt er að hún verði samþykkt – ekki bara vegna Íslendinga, heldur líka fyrir Evrópubúa og aðra.",
        "Senn líður að því að Bretar greiði atkvæði um áframhaldandi veru sína í Evrópusambandinu, og það hefur sjaldan verið svona erfitt að vera meðmæltur því að halda aðild áfram. Heimsálfan situr föst í varanlegri efnahagskreppu, hægri öfgaöflum vex fiskur um hrygg í mörgum aðildarríkjanna, og landamærin sem heyrðu fortíðinni til hafa verið dregin upp að nýju. Samstaða og valdajafnvægi Evrópusambandsins hefur verið vefengt, ekki síst vegna þess hvernig gríska stjórnin var þvinguð til þess að taka upp aðhaldsstefnu þvert á vilja þjóðarinnar, og sjálfur Alþjóðagjaldeyrissjóðurinn hefur sagt að slík stefna væri ekki tæk. Á Twitter má slá upp #thisisacoup, þræði sem spratt fram eftir að deila Grikkja og ESB hafði verið leyst til bráðabirgða í júní í fyrra. Þar má sjá dæmi um það hvað lýðræðið er orðið brothætt í Evrópu.",
        "Þó eru rökin í þágu „Brexit“ (brotthvarf Breta úr ESB) ekki mjög sannfærandi heldur. Lífskjör breskrar alþýðu versna með hverri hrinu aðhaldsaðgerða, og aðgerðir hins opinbera til þess að sporna fæti við „öfgastefnum“ hafa haft hrollvekjandi áhrif á fjölbreytta, lýðræðislega umræðu. Seinna á árinu verða líklega samþykkt lög um rétt til rannsókna, og þar með verður almennt eftirlit, sem Snowden gagnrýndi með uppljóstrunum sínum, útfært og lögfest.",
        "Skilyrðin til þess að styrkja og efla lýðræðið eru ef til vill ekki sem best á tímum efnahagskreppu og ótta við hryðjuverk. Á slíkum tímum er þó einmitt hvað brýnust þörfin á opinni umræðu og almennum skoðanaskiptum, og þá er líka þörf á nýbreytni, róttækum lausnum og raunverulegum breytingum. Þess vegna hefur mörgum verið það hvatning að líta til Íslands. Þar leiddi efnahagskreppan til verulegra breytinga á vettvangi stjórnmála og efnahags. Tillögur að stefnubreytingum á borð við þær, sem kynntar eru hjá Alþjóðlegri stofnun um upplýsinga- & tjáningarfrelsi (IMMI) gerðu ráð fyrir nýjum, heildrænum leiðum til framfara fyrir landið, og ný stjórnarskrá var samin í opnu og heildrænu grasrótarferli, stjórnarskrá þjóðarinnar, fyrir þjóðina. Nefnd íslenskra ríkisborgara, stjórnlagaráð, samdi textann, almenningur lagði til þúsundir athugasemda, og árangurinn var samþykktur með þjóðaratkvæðagreiðslu.",
        "Þannig hefur íslenska þjóðin valið sér sérstaklega lýðræðislega leið út úr kreppunni og á vit framtíðarinnar. Hún hefur sýnt að andlaus kyrrstaðan, sem nú einkennir stjórnmál í Evrópu, ásamt einræðis- og útilokunartilburðum, er ekki sjálfgefið viðbragð við öryggisógnum og erfiðum efnahag. Þvert á móti hefur hún sýnt fram á að lýðræðið er lifandi, þrátt fyrir allt og á þessum tímum, og að við, borgararnir, getum skapað okkur nýjan grundvöll fyrir því ríki sem við viljum, og því lífi sem við kjósum okkur.",
        "Nú ríkir mikil óvissa í allri Evrópu að því er varðar þessi mál. Íslenska þjóðin sýndi mikið hugrekki þegar hún réðst í það verkefni að semja sér nýja stjórnarskrá, og hefur það haft áhrif langt út fyrir eylandið. Þetta er vísbending um þá leið sem kann að vera fær til þess að takast á við vandann sem við er að etja, og um allan heim fylgjast menn grannt með framhaldinu. Það, hvernig nýja stjórnarskráin var samin og samþykkt með þjóðaratkvæðagreiðslu, hefur orðið mörgum hvatning út fyrir landsteinana, og nú vona þeir að Alþingi hætti að tefja framgang þessa sögulega verkefnis. Það yrði ekki aðeins til vitnis um það, hvað lýðræðið stendur traustum fótum á Íslandi, heldur yrði það líka mikilvægt dæmi til eftirbreytni, um lýðræðislega leið út úr kreppu og óvissu."
      ],
    }
  }, {
    title: {
      EN: "Participate the Icelandic Way: What A Crowdsourced Constitution Can Teach Us About Direct Democracy In a post-Brexit World",
      IS: "Þátttaka með íslensku sniði: Hvað getur stjórnarskrá, sem samin er með almennri þátttöku, kennt okkur um beint lýðræði eftir Brexit",
    },
    languages: ["IS"],
    author: "Ragnar Aðalsteinsson",
    translator: "",
    authorPics: ["/img/authors/adalsteinsson.jpg"],
    authorBios: {
      EN: ["Ragnar Aðalsteinsson, Attorney for the Supreme Court of Iceland."],
      IS: ["Ragnar Aðalsteinsson hæstaréttar­lögmaður."]
    },
    text: {
      EN: [
        "(No English translation available.)",
      ],
      IS: [
        "Í stjórnarskrárfrumvarpi Stjórnlagaráðs eru markverðar nýjungar um náttúruauðlindir í þjóðareign. Spurt var um afstöðu kjósenda til frumvarpsins í þjóðar­atkvæðagreiðslu árið 2012. Tveir þriðju kjósenda sögðust vilja leggja drög Stjórnlagaráðs til grundvallar nýrri stjórnarskrá og enn stærri hluti, eða um 75% kjósenda, sagðist samþykkur því að í nýrri stjórnarskrá yrðu náttúruauðlindir, sem ekki eru í einkaeigu, lýstar sem þjóðareign.",
        "Ákvæði Stjórnlagaráðs var samið af óháðum og sjálfstæðum fulltrúum, sem þjóðin hafði til þess kjörið, og Alþingi svo skipað eftir ógildingu Hæstaréttar á grundvelli formsatriða. Ráðið vann verkefnið fyrir opnum tjöldum og tók sjónarmiðum almennings opnum örmum og gaumgæfði þau. Ráðsmenn komust að sameiginlegum niðurstöðum um efni og orðalag nýrrar stjórnarskrár fyrir landið. Stjórnarskrárfrumvarpið var þannig samið á lýðræðislegan hátt.",
        "Sanngjarn mælikvarði",
        "Þeim, sem hafa hug á að endursemja og breyta tillögum ráðsins, er vandi á höndum, því færa má að því rök að þeir, sem það reyna, verði að færa á það ótvíræðar sönnur að breytingartillögur þeirra séu betur til þess fallnar að treysta almannahag en tillögur ráðsins. Það virðist sanngjarn mælikvarði, sem bregða má á nýbirtar tillögur stjórnarskrárnefndar.",
        "Í tillögum ráðsins að ákvæði um náttúruauðlindir eru notuð hugtökin einkaeign og eign, sem eru í gildandi stjórnarskrá og hafa tiltölulega skýra merkingu. Í stað þess að nota svo glögg og afmörkuð hugtök er í tillögum stjórnarskrárnefndar Alþingis, sem nú hafa verið birtar, notað hugtakið að tilheyra sem gerir merkinguna óljósa. Það hugtak táknar ekki eignarréttarlegt samband í tillögum nefndarinnar. Merking þess er óljós og veldur túlkunarvanda. Nefndin viðurkennir í skýringum sínum að ekki sé vísað til hefðbundins eignarréttar. Síðar í ákvæðinu leggur nefndin til að náttúruauðlindir sem ekki eru háðar einkaeignarrétti séu þjóðareign. Enn notar nefndin hið óljósa hugtak að eitthvað sé háð einkaeignarrétti í stað þess að nota eins skýr hugtök og unnt er, í þessu tilviki auðlindir í einkaeign.",
        "Náttúruauðlindahugtak nefndarinnar er ekki skilgreint að neinu leyti í ákvæðinu sjálfu og er því látið Alþingi eftir. Í tillögum ráðsins er að finna skilgreiningu, sem er nægilega sveigjanleg til að koma til móts við nýjar aðstæður og þekkingu, en er jafnframt hæfilegt aðhald að löggjafarvaldinu og leiðbeinandi fyrir dómstóla.",
        "Opnar fyrir geðþóttaákvarðanir",
        "Um gjaldtöku af þeim sem fá leyfi til að nýta auðlindir í þjóðareign segir í tillögum ráðsins að leyfishafar skuli greiða fullt gjald fyrir og er fyrirmyndina að því orðalagi að finna í ákvæði stjórnarskrárinnar um eignarnám. Nefnd Alþingis leggur hins vegar til að að jafnaði skuli taka eðlilegt gjald fyrir leyfi til nýtingar. Með því að nota hugtakið að jafnaði er leitast við veita Alþingi víðtæka heimild til að ákveða hvort gjald skuli taka af leyfishafa eða ekki. Með hugtakinu eðlilegt gjald er því einnig veitt víðtæk heimild til að ákveða gjaldið án tillits til verðmætis nýtingarleyfisins fyrir þann sem þess nýtur. Orðalagið opnar fyrir geðþótta­ákvarðanir í andstöðu við almannahag.",
        "Þá er í tillögum ráðsins lagt til að afnota- eða nýtingarleyfi verði einungis veitt til tiltekins hóflegs tíma í senn. Nefndin gerir ekki tillögu um slíka takmörkun á nýtingartímanum. Rökin fyrir takmörkuninni eru m.a. þau, að heimil langtímanýting getur í raun jafnast á við yfirfærslu eignarréttar.",
        "Leitast við að hafa áhrif",
        "Þá er það gagnrýnisvert hvernig nefndin leitast við að hafa áhrif á túlkun ákvæðisins með því að gefa í skyn í greinargerð að gildandi nýtingarheimildir – og er þá átt við fisksveiðiheimildir – kunni að hafa stofnað til annarra og víðtækari réttinda en lög mæla fyrir um meðal annars með fyrirvaranum í lögum um stjórn fiskveiða um að nytjastofnar á Íslandsmiðum skuli vera sameign þjóðarinnar.",
        "Af framangreindum samanburði er ljóst að ég tel að tillögur Stjórnlagaráðs beri vott um stjórnvisku og góðan skilning á þýðingu þess að texti í stjórnarskrá sé eins glöggur og unnt er og gefi sem minnst tilefni til mismunandi skilnings og þar með ágreinings á Alþingi og fyrir dómstólum.",
        "Ísland er ríkt af auðlindum og gæfa og gengi þeirra sem nú búa hér og komandi kynslóða ræðst af því hvernig til tekst við varðveislu og nýtingu auðlinda landsins á sjálfbæran hátt. Mikilvægt tæki til að ná því markmiði er ákvæði í stjórnarskrá sem tryggir að auðlindum þessum verði ekki sóað þannig að ekki verði lífvænlegt í landinu til frambúðar. Alþingi verður að hafa það í huga er það tekur afstöðu til þessara tveggja tillagna.",
      ],
    }
  }, ],
};
